/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Modifiers: typeof import('./src/components/modifiers.vue')['default']
    Perks: typeof import('./src/components/perks.vue')['default']
    Perkshud: typeof import('./src/components/perkshud.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Startstop: typeof import('./src/components/startstop.vue')['default']
  }
}
